repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: name-tests-test
      - id: pretty-format-json
        name: pretty format json
        description: sets a standard for formatting json files.
        entry: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-ensure-ascii"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        name: blue
        description: "Blue: The somewhat less uncompromising Python code formatter"
        entry: blue
        language: python
        language_version: python3
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]
